### ISSUE TITLE
Add Difficulty and Creature Charms

### ISSUE THREAD

**Issue by nickcamastra** [benjaminkomen/TibiaWikiApi#167]
Could you add the Difficulty and Creature Charms? I love what you have done. Thank you very much for that.

**Comment by benjaminkomen** [comment]
Sure, I'll take a look at it soon.

**Comment by nickcamastra** [comment]
> Seguro, lo echaré un vistazo pronto.
> 
> * Admite [encantos](https://tibia.fandom.com/wiki/Template:Infobox_Charm) como, por ejemplo, [Adrenaline Burst](https://tibia.fandom.com/wiki/Adrenaline_Burst)
> 
> @nickcamastra , ¿a qué te refieres con dificultad?

Skip the '**difficulty**', I already found it, it was **bestiarylevel**. But the **creature charms** do not appear: 
[https://tibia.fandom.com/wiki/Dragon](url) (25 charm points)
https://tibiawiki.dev/api/creatures/Dragon (do not appear number of charms)

**Comment by nickcamastra** [comment]
And thank you very much for adding the Charms

**Comment by benjaminkomen** [comment]
Ah I see, thee charm points you see on e.g. the Dragon page are added by https://tibia.fandom.com/wiki/Template:Charm_Points using *bestiarylevel* and *occurrence*. So it's not in the source data of a creature, but can be derived from those two data fields I mentioned.
