### ISSUE TITLE
getItems API not working

### ISSUE THREAD

**Issue by Glatharth** [benjaminkomen/TibiaWikiApi#216]
it is returning [] as shown in print
https://tibiawiki.dev/swagger-ui/index.html?configUrl=/api-docs/swagger-config#/Items/getItems

![image](https://user-images.githubusercontent.com/39601778/138105373-5676fd3a-3b60-439e-a731-0e5d4b899b16.png)

**Comment by benjaminkomen** [comment]
Suggestion, use Category:Pickupable Items

**Comment by benjaminkomen** [comment]
This has been fixed in the referenced PR. The endpoint https://tibiawiki.dev/api/items now returns a list of items again.
